title: Blog Nghề Code - Nơi lưu lại những bài viết về nghề ... 
email: nty.nod@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tôi dùng blog này làm nơi lưu lại những kiến thức của mình trong quá trình làm việc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Nghề Code # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: nghecode  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: nhamtybv@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
