# SITE CONFIGURATION
baseurl: ""
url: "https://nghecode.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Blog Nghề Code
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Nơi chia sẽ kiến thức lượm lặt trong quảng đời code mướn." # used by search engines

  # Header and footer text
  header_text: >
    <p>
      Knowledge in the head and virtue in the heart, time devoted to study or business, instead of show and pleasure, are the way to be useful and consequently happy.
      <br/>
      <code>John Adams</code>
    </p>
  header_text_feature_image:
  footer_text: >
    Được xây dựng bởi <a href="nhamtybv@gmail.com" >Nham Ty</a>
  # Icons
  rss: false
  email_address: nhamtybv@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "Rvor"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/nhâm-tý-8ba6213a/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "Rvor"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Tìm hiểu thêm"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
